FROM ubuntu:latest
RUN \
        apt-get update && \
        apt-get install vim -y
WORKDIR /home/dpdk
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/dpdk/x86_64-native-linuxapp-gcc/app/
